require "svetly.options"
require "svetly.plugins"
require "svetly.functions"
require "svetly.keymaps"
-- require "svetly.plugins-native"
-- require "svetly.plugins-settings"
-- require "svetly.colorscheme"
-- require "svetly.cmp"
-- require "svetly.lsp"
